export const data= [
  {
    "id": 1,
    "name": "Rose",
    "category": "Flowering Plants",
    "description": "Roses are one of the most popular and well-known ornamental plants. They are prized for their beauty and fragrance.",
    "price": 10.99,
    "availability": "In Stock",
    "size": "Medium",
    "light_requirements": "Full Sun",
    "watering_requirements": "Moderate Water",
    "soil_type": "Loamy",
    "img": ""
  },
  {
    "id": 2,
    "name": "Jasmine",
    "category": "Flowering Plants",
    "description": "Jasmine is a fragrant flowering plant that is prized for its beauty and scent. It is commonly used in perfumes and teas.",
    "price": 7.99,
    "availability": "In Stock",
    "size": "Small",
    "light_requirements": "Partial Sun",
    "watering_requirements": "Low Water",
    "soil_type": "Sandy",
    "img": ""
  },
  {
    "id": 3,
    "name": "Bougainvillea",
    "category": "Flowering Plants",
    "description": "Bougainvillea is a popular ornamental plant that is prized for its brightly colored flowers. It is often used as a climbing vine or in hanging baskets.",
    "price": 14.99,
    "availability": "In Stock",
    "size": "Large",
    "light_requirements": "Full Sun",
    "watering_requirements": "Low Water",
    "soil_type": "Sandy",
    "img": ""
  },
  {
    "id": 4,
    "name": "Hibiscus",
    "category": "Flowering Plants",
    "description": "Hibiscus is a beautiful flowering plant that is prized for its large, colorful blooms. It is often used in gardens and as a houseplant.",
    "price": 9.99,
    "availability": "In Stock",
    "size": "Medium",
    "light_requirements": "Full Sun",
    "watering_requirements": "Moderate Water",
    "soil_type": "Loamy",
    "img": ""
  },
  {
    "id": 5,
    "name": "Geranium",
    "category": "Flowering Plants",
    "description": "Geraniums are a popular garden plant, known for their bright colors and long blooming season. They come in a variety of colors and sizes, and are easy to care for.",
    "price": 7.99,
    "availability": "In Stock",
    "size": "Small",
    "light_requirements": "Full Sun",
    "watering_requirements": "Moderate Water",
    "soil_type": "Well-Draining",
    "img": ""
  },
  {
    "id": 6,
    "name": "Oleander",
    "category": "Flowering Plants",
    "description": "Oleander is a popular shrub with beautiful flowers. However, it is toxic and should be handled with care.",
    "price": 8.99,
    "availability": "In Stock",
    "size": "Large",
    "light_requirements": "Full Sun",
    "watering_requirements": "Low Water",
    "soil_type": "Sandy",
    "img": ""
    },
    {
    "id": 7,
    "name": "Iris",
    "category": "Bulbs",
    "description": "Iris is a beautiful bulbous plant with distinctive flowers. They come in a variety of colors and are easy to grow.",
    "price": 5.99,
    "availability": "In Stock",
    "size": "Medium",
    "light_requirements": "Full Sun, Partial Shade",
    "watering_requirements": "Moderate Water",
    "soil_type": "Well-Drained",
    "img": ""
    },
    {
    "id": 8,
    "name": "Pansy",
    "category": "Annual Plants",
    "description": "Pansies are a popular bedding plant known for their colorful, heart-shaped flowers. They are easy to grow and can bloom in both spring and fall.",
    "price": 3.99,
    "availability": "In Stock",
    "size": "Small",
    "light_requirements": "Partial Shade",
    "watering_requirements": "Moderate Water",
    "soil_type": "Loamy",
    "img": ""
    },
    {
    "id": 9,
    "name": "Petunia",
    "category": "Annual Plants",
    "description": "Petunias are a popular bedding plant with trumpet-shaped flowers. They come in a variety of colors and can bloom throughout the summer.",
    "price": 4.99,
    "availability": "In Stock",
    "size": "Medium",
    "light_requirements": "Full Sun",
    "watering_requirements": "Moderate Water",
    "soil_type": "Loamy",
    "img": ""
    },
    {
    "id": 10,
    "name": "Marigold",
    "category": "Flowering Plants",
    "description": "Marigolds are easy-to-grow annual plants that are prized for their bright, showy flowers. They come in a variety of colors and can be used in borders, beds, and containers.",
    "price": 5.99,
    "availability": "In Stock",
    "size": "Small",
    "light_requirements": "Full Sun",
    "watering_requirements": "Low Water",
    "soil_type": "Well-draining",
    "img": ""
    },
    {
    "id": 11,
    "name": "Sunflower",
    "category": "Flowering Plants",
    "description": "Sunflowers are tall, bold annual plants that produce large, showy flowers. They are easy to grow and are often used in gardens and as cut flowers.",
    "price": 8.99,
    "availability": "In Stock",
    "size": "Large",
    "light_requirements": "Full Sun",
    "watering_requirements": "Moderate Water",
    "soil_type": "Well-draining",
    "img": ""
    },
    {
    "id": 12,
    "name": "Zinnia",
    "category": "Flowering Plants",
    "description": "Zinnias are popular annual plants that come in a wide variety of colors and sizes. They are easy to grow and are often used in borders, beds, and containers.",
    "price": 6.99,
    "availability": "In Stock",
    "size": "Small",
    "light_requirements": "Full Sun",
    "watering_requirements": "Moderate Water",
    "soil_type": "Well-draining",
    "img": ""
    },
    {
    "id": 13,
    "name": "Daffodil",
    "category": "Flowering Plants",
    "description": "Daffodils are popular spring-blooming bulbs that produce large, showy flowers. They are easy to grow and are often used in gardens and as cut flowers.",
    "price": 12.99,
    "availability": "In Stock",
    "size": "Medium",
    "light_requirements": "Full Sun, Partial Shade",
    "watering_requirements": "Moderate Water",
    "soil_type": "Well-draining",
    "img": ""
    },
    {
    "id": 14,
    "name": "Narcissus",
    "category": "Bulbous Plants",
    "description": "Narcissus is a genus of predominantly spring flowering perennial plants of the Amaryllidaceae family.",
    "price": 8.99,
    "availability": "In Stock",
    "size": "Medium",
    "light_requirements": "Full Sun, Partial Shade",
    "watering_requirements": "Low to Moderate Water",
    "soil_type": "Well-drained, Loamy",
    "img": ""
  },
  {
    "id": 15,
    "name": "Tulip",
    "category": "Bulbous Plants",
    "description": "Tulips are a genus of spring-blooming perennial herbaceous bulbiferous geophytes.",
    "price": 12.99,
    "availability": "In Stock",
    "size": "Medium",
    "light_requirements": "Full Sun",
    "watering_requirements": "Moderate Water",
    "soil_type": "Well-drained, Loamy",
    "img": ""
  },
  {
    "id": 16,
    "name": "Hyacinth",
    "category": "Bulbous Plants",
    "description": "Hyacinths are spring-blooming bulbs with fragrant flowers. They are often used for garden decoration or as indoor plants.",
    "price": 9.99,
    "availability": "In Stock",
    "size": "Small to Medium",
    "light_requirements": "Full Sun, Partial Shade",
    "watering_requirements": "Low to Moderate Water",
    "soil_type": "Well-drained, Loamy",
    "img": ""
  },
  {
    "id": 17,
    "name": "Fuchsia",
    "category": "Flowering Plants",
    "description": "Fuchsias are popular garden plants, grown for their very attractive, usually pendent flowers that are borne in summer and autumn.",
    "price": 7.99,
    "availability": "In Stock",
    "size": "Medium to Large",
    "light_requirements": "Partial Shade",
    "watering_requirements": "Moderate Water",
    "soil_type": "Well-drained, Humus-rich",
    "img": ""
  },
  {
    "id":18,
    "name":"Lavender",
    "category":"Herbs",
    "description":"Lavender is a fragrant herb that is commonly used in perfumes, soaps, and other personal care products.",
    "price":6.99,
    "availability":"In Stock",
    "size":"Medium",
    "light_requirements":"Full Sun",
    "watering_requirements":"Low Water",
    "soil_type":"Well-Draining",
    "img":""
 },
 {
    "id":19,
    "name":"Sage",
    "category":"Herbs",
    "description":"Sage is a popular herb that is often used in cooking, particularly in Mediterranean and Middle Eastern cuisines.",
    "price":5.99,
    "availability":"In Stock",
    "size":"Small",
    "light_requirements":"Full Sun",
    "watering_requirements":"Low Water",
    "soil_type":"Well-Draining",
    "img":""
 },
 {
    "id":20,
    "name":"Mint",
    "category":"Herbs",
    "description":"Mint is a versatile herb that is commonly used in teas, desserts, and other culinary creations.",
    "price":4.99,
    "availability":"In Stock",
    "size":"Small",
    "light_requirements":"Partial Sun",
    "watering_requirements":"Moderate Water",
    "soil_type":"Moist",
    "img":""
 },
 {
    "id":21,
    "name":"Basil",
    "category":"Herbs",
    "description":"Basil is a fragrant herb that is used in a variety of cuisines, including Italian, Thai, and Vietnamese.",
    "price":7.99,
    "availability":"In Stock",
    "size":"Medium",
    "light_requirements":"Full Sun",
    "watering_requirements":"Moderate Water",
    "soil_type":"Well-Draining",
    "img":""
 },
 {
    "id":22,
    "name":"Thyme",
    "category":"Herbs",
    "description":"Thyme is a fragrant herb that is commonly used in Mediterranean and Middle Eastern cuisine.",
    "price":4.99,
    "availability":"In Stock",
    "size":"Small",
    "light_requirements":"Full Sun",
    "watering_requirements":"Low Water",
    "soil_type":"Well-draining",
    "img":""
  },
  {
    "id":23,
    "name":"Oregano",
    "category":"Herbs",
    "description":"Oregano is a popular herb that is often used in Italian and Greek dishes.",
    "price":5.99,
    "availability":"In Stock",
    "size":"Small",
    "light_requirements":"Full Sun",
    "watering_requirements":"Low Water",
    "soil_type":"Well-draining",
    "img":""
  },
  {
    "id":24,
    "name":"Rosemary",
    "category":"Herbs",
    "description":"Rosemary is a versatile herb that is commonly used in Mediterranean cuisine and is known for its aromatic and flavorful leaves.",
    "price":6.99,
    "availability":"In Stock",
    "size":"Medium",
    "light_requirements":"Full Sun",
    "watering_requirements":"Low Water",
    "soil_type":"Well-draining",
    "img":""
  },
  {
    "id":25,
    "name":"Chives",
    "category":"Herbs",
    "description":"Chives are a mild-flavored herb that is often used in French cuisine and are characterized by their long, thin leaves.",
    "price":3.99,
    "availability":"In Stock",
    "size":"Small",
    "light_requirements":"Full Sun to Partial Shade",
    "watering_requirements":"Moderate Water",
    "soil_type":"Well-draining",
    "img":""
  },
  {
    "id": 26,
    "name": "Parsley",
    "category": "Herbs",
    "description": "Parsley is a versatile herb used in a wide variety of dishes. It is rich in vitamins and minerals.",
    "price": 4.99,
    "availability": "In Stock",
    "size": "Small",
    "light_requirements": "Full Sun, Partial Shade",
    "watering_requirements": "Regular Water",
    "soil_type": "Well-draining",
    "img": ""
  },
  {
    "id": 27,
    "name": "Coriander",
    "category": "Herbs",
    "description": "Coriander is a popular herb used in many different cuisines. It is known for its unique flavor and aroma.",
    "price": 5.99,
    "availability": "In Stock",
    "size": "Small",
    "light_requirements": "Full Sun, Partial Shade",
    "watering_requirements": "Regular Water",
    "soil_type": "Well-draining",
    "img": ""
  },
  {
    "id": 28,
    "name": "Cactus",
    "category": "Succulents",
    "description": "Cacti are low-maintenance plants that are perfect for busy people. They come in a wide variety of shapes and sizes.",
    "price": 12.99,
    "availability": "In Stock",
    "size": "Small",
    "light_requirements": "Full Sun",
    "watering_requirements": "Infrequent Water",
    "soil_type": "Well-draining",
    "img": ""
  },
  {
    "id": 29,
    "name": "Aloe Vera",
    "category": "Succulents",
    "description": "Aloe vera is a popular plant known for its healing properties. It is easy to care for and can be used in a variety of ways.",
    "price": 14.99,
    "availability": "In Stock",
    "size": "Medium",
    "light_requirements": "Full Sun",
    "watering_requirements": "Infrequent Water",
    "soil_type": "Well-draining",
    "img": ""
  },
  {
    "id": 30,
    "name": "Pothos",
    "category": "Indoor Plants",
    "description": "Pothos is a low-maintenance trailing plant that can be grown in a variety of lighting conditions. Its leaves come in a variety of shades, including green, yellow, and variegated.",
    "price": 12.99,
    "availability": "In Stock",
    "size": "Small",
    "light_requirements": "Low to Medium Light",
    "watering_requirements": "Low Water",
    "soil_type": "Well-Draining",
    "img": ""
  },
  {
    "id": 31,
    "name": "Spider Plant",
    "category": "Indoor Plants",
    "description": "Spider plants are popular for their long, thin foliage and small white flowers. They are easy to grow and can thrive in a variety of environments.",
    "price": 9.99,
    "availability": "In Stock",
    "size": "Small",
    "light_requirements": "Bright to Medium Light",
    "watering_requirements": "Moderate Water",
    "soil_type": "Well-Draining",
    "img": ""
  },
  {
    "id": 32,
    "name": "Snake Plant",
    "category": "Indoor Plants",
    "description": "Snake plants are known for their tall, sturdy leaves and ability to thrive in low-light conditions. They are also known for their air-purifying properties.",
    "price": 14.99,
    "availability": "In Stock",
    "size": "Medium",
    "light_requirements": "Low to Bright Light",
    "watering_requirements": "Low Water",
    "soil_type": "Well-Draining",
    "img": ""
  },
  {
    "id": 33,
    "name": "Dracaena",
    "category": "Indoor Plants",
    "description": "Dracaena is a popular houseplant with long, narrow leaves that come in a variety of colors, including green, yellow, and red. It is a low-maintenance plant that can thrive in a variety of lighting conditions.",
    "price": 16.99,
    "availability": "In Stock",
    "size": "Medium",
    "light_requirements": "Low to Bright Light",
    "watering_requirements": "Moderate Water",
    "soil_type": "Well-Draining",
    "img": ""
  },
  {
    "id":34,
    "name":"Peace Lily",
    "category":"Indoor Plants",
    "description":"The Peace Lily is a popular indoor plant known for its ability to improve air quality and remove toxins from the air.",
    "price":25.99,
    "availability":"In Stock",
    "size":"Small",
    "light_requirements":"Low to Medium Light",
    "watering_requirements":"Moderate Water",
    "soil_type":"Well-Draining",
    "img":""
  },
  {
    "id":35,
    "name":"English Ivy",
    "category":"Indoor Plants",
    "description":"English Ivy is a popular trailing plant with small, pointed leaves that are often variegated. It is a great choice for indoor hanging baskets or to climb walls.",
    "price":20.99,
    "availability":"In Stock",
    "size":"Small",
    "light_requirements":"Low to Medium Light",
    "watering_requirements":"Moderate Water",
    "soil_type":"Well-Draining",
    "img":""
  },
  {
    "id":36,
    "name":"Croton",
    "category":"Indoor Plants",
    "description":"Crotons are tropical plants known for their colorful foliage. They are great for adding a pop of color to your indoor space.",
    "price":30.99,
    "availability":"In Stock",
    "size":"Medium",
    "light_requirements":"High Light",
    "watering_requirements":"Moderate Water",
    "soil_type":"Well-Draining",
    "img":""
  },
  {
    "id":37,
    "name":"Ficus",
    "category":"Indoor Plants",
    "description":"Ficus is a popular indoor tree known for its large, glossy leaves. It is a great statement piece for any indoor space.",
    "price":35.99,
    "availability":"In Stock",
    "size":"Large",
    "light_requirements":"Medium to High Light",
    "watering_requirements":"Moderate Water",
    "soil_type":"Well-Draining",
    "img":""
  },
  
  {
    "id":38,
    "name":"Rubber Plant",
    "category":"Indoor Plants",
    "description":"The Rubber Plant is a popular indoor plant known for its large, shiny leaves. It can grow up to 8 feet tall and requires moderate watering.",
    "price":24.99,
    "availability":"In Stock",
    "size":"Medium",
    "light_requirements":"Medium to High Light",
    "watering_requirements":"Moderate Water",
    "soil_type":"Well-draining soil",
    "img":""
 },
 {
    "id":39,
    "name":"Amaryllis",
    "category":"Flowering Plants",
    "description":"The Amaryllis is a beautiful flowering plant that blooms in the winter. It comes in many colors and can grow up to 2 feet tall.",
    "price":12.99,
    "availability":"Out of Stock",
    "size":"Small",
    "light_requirements":"Full Sun",
    "watering_requirements":"Moderate Water",
    "soil_type":"Well-draining soil",
    "img":""
 },
 {
    "id":40,
    "name":"Cyclamen",
    "category":"Flowering Plants",
    "description":"The Cyclamen is a popular indoor plant known for its beautiful, brightly colored flowers. It requires cool temperatures and moderate watering.",
    "price":18.99,
    "availability":"In Stock",
    "size":"Small",
    "light_requirements":"Medium to High Light",
    "watering_requirements":"Moderate Water",
    "soil_type":"Well-draining soil",
    "img":""
 },
 {
    "id":41,
    "name":"Chrysanthemum",
    "category":"Flowering Plants",
    "description":"The Chrysanthemum is a popular outdoor plant known for its beautiful, colorful flowers. It requires full sun and moderate watering.",
    "price":8.99,
    "availability":"In Stock",
    "size":"Medium",
    "light_requirements":"Full Sun",
    "watering_requirements":"Moderate Water",
    "soil_type":"Well-draining soil",
    "img":""
 },
 {
    "id": 42,
    "name": "Delphinium",
    "category": "Flowering Plants",
    "description": "Delphinium is a tall and elegant flowering plant known for its long spikes of blue or purple flowers. It is a popular choice for cottage gardens.",
    "price": 12.99,
    "availability": "In Stock",
    "size": "Large",
    "light_requirements": "Full Sun to Partial Shade",
    "watering_requirements": "Regular Water",
    "soil_type": "Well-draining",
    "img": ""
  },
  {
    "id": 43,
    "name": "Phlox",
    "category": "Flowering Plants",
    "description": "Phlox is a low-growing plant that produces clusters of small, fragrant flowers in shades of pink, purple, and white. It is a great choice for rock gardens or as a ground cover.",
    "price": 9.99,
    "availability": "In Stock",
    "size": "Small",
    "light_requirements": "Full Sun",
    "watering_requirements": "Regular Water",
    "soil_type": "Well-draining",
    "img": ""
  },
  {
    "id": 44,
    "name": "Sweet Pea",
    "category": "Flowering Plants",
    "description": "Sweet pea is a climbing plant that produces clusters of fragrant flowers in shades of pink, purple, and white. It is a great choice for trellises or arbors.",
    "price": 11.99,
    "availability": "In Stock",
    "size": "Medium",
    "light_requirements": "Full Sun to Partial Shade",
    "watering_requirements": "Regular Water",
    "soil_type": "Well-draining",
    "img": ""
  },
  {
    "id": 45,
    "name": "Gardenia",
    "category": "Flowering Plants",
    "description": "Gardenia is a flowering plant known for its large, fragrant white flowers. It is a popular choice for indoor and outdoor gardens.",
    "price": 14.99,
    "availability": "In Stock",
    "size": "Medium",
    "light_requirements": "Partial Shade",
    "watering_requirements": "Regular Water",
    "soil_type": "Well-draining",
    "img": ""
  },
  {
    "id":46,
    "name":"Stock",
    "category":"Flowering Plants",
    "description":"Stocks are prized for their delicate, sweetly scented flowers that come in shades of pink, purple, white, and red.",
    "price":8.99,
    "availability":"In Stock",
    "size":"Small",
    "light_requirements":"Full Sun",
    "watering_requirements":"Moderate Water",
    "soil_type":"Well-draining",
    "img":""
 },
 {
    "id":47,
    "name":"Fritillaria",
    "category":"Bulbs",
    "description":"Fritillarias are bulbous plants that are known for their unusual bell-shaped flowers that bloom in shades of purple, white, and yellow.",
    "price":12.99,
    "availability":"In Stock",
    "size":"Medium",
    "light_requirements":"Full Sun to Partial Shade",
    "watering_requirements":"Moderate Water",
    "soil_type":"Well-draining",
    "img":""
 },
 {
    "id":48,
    "name":"Crocus",
    "category":"Bulbs",
    "description":"Crocuses are small, hardy bulbs that bloom in late winter to early spring, providing a welcome burst of color after the winter months.",
    "price":6.99,
    "availability":"In Stock",
    "size":"Small",
    "light_requirements":"Full Sun",
    "watering_requirements":"Moderate Water",
    "soil_type":"Well-draining",
    "img":""
 },
 {
    "id":49,
    "name":"Scabiosa",
    "category":"Flowering Plants",
    "description":"Scabiosas are popular garden plants that are known for their dainty, pin-cushion-like flowers that come in shades of pink, purple, and white.",
    "price":9.99,
    "availability":"In Stock",
    "size":"Medium",
    "light_requirements":"Full Sun",
    "watering_requirements":"Moderate Water",
    "soil_type":"Well-draining",
    "img":""
 },
 {
    "id": 50,
    "name": "Anemone",
    "category": "Flowering Plants",
    "description": "Anemones are beautiful, delicate flowers that bloom in a range of colors. They are often used in floral arrangements and can add a touch of elegance to any garden.",
    "price": 5.99,
    "availability": "In Stock",
    "size": "Small",
    "light_requirements": "Partial Shade",
    "watering_requirements": "Moderate Water",
    "soil_type": "Well-Draining",
    "img": ""
  },
  {
    "id": 51,
    "name": "Lemon Plant",
    "category": "Fruit Trees",
    "description": "Lemon trees are a popular choice for home gardens due to their delicious fruit and beautiful appearance. They require a sunny spot and moderate watering to thrive.",
    "price": 29.99,
    "availability": "In Stock",
    "size": "Medium",
    "light_requirements": "Full Sun",
    "watering_requirements": "Moderate Water",
    "soil_type": "Well-Draining",
    "img": ""
  }
]